# Basic Tensor operations and GradientTape.

In this notebook, we will perform various tensor operations and use [GradientTape](https://www.tensorflow.org/api_docs/python/tf/GradientTape).

In [ ]:
import tensorflow as tf
import numpy as np

Let's start by creating a constant tensor from a tensor-like object. It's a straightforward method to ensure that the data structure used remains unchanged and immutable throughout the operation, making it ideal for storing static data in TensorFlow applications

In [ ]:
# Convert NumPy array to Tensor using `tf.constant`
def tf_constant(array):
    """
    Args:
        array (numpy.ndarray): tensor-like array.

    Returns:
        tensorflow.python.framework.ops.EagerTensor: tensor.
    """

    tf_constant_array = tf.constant(array)

    return tf_constant_array

In [ ]:
tmp_array = np.arange(1,10)
x = tf_constant(tmp_array)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

For future documentation, the term `EagerTensor` will be used as a concise reference for `tensorflow.python.framework.ops.EagerTensor`. This shorthand helps streamline communications and documentation by using a simplified label for this specific tensor type within TensorFlow.

## Exercise 2 - [tf.square](https://www.tensorflow.org/api_docs/python/tf/math/square)

Computes the square of a tensor element-wise.

In [ ]:
# Square the input tensor
def tf_square(array):
    """
    Args:
        array (numpy.ndarray): tensor-like array.

    Returns:
        EagerTensor: tensor.
    """
    # Make sure it's a tensor
    array = tf.constant(array)

    tf_squared_array = tf.square(array)

    return tf_squared_array

In [ ]:
tmp_array = tf.constant(np.arange(1, 10))
x = tf_square(tmp_array)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

We can also reshape a tensor using `tf.reshape`

In [ ]:
# Reshape tensor into the given shape parameter
def tf_reshape(array, shape):
    """
    Args:
        array (EagerTensor): tensor to reshape.
        shape (tuple): desired shape.

    Returns:
        EagerTensor: reshaped tensor.
    """
    # Make sure it's a tensor
    array = tf.constant(array)

    tf_reshaped_array = tf.reshape(array, shape)

    return tf_reshaped_array

In [ ]:
# Check the function
tmp_array = np.array([1,2,3,4,5,6,7,8,9])
# Check that the function reshapes a vector into a matrix
x = tf_reshape(tmp_array, (3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

A tensor can be casted to a new type using `tf.cast`

In [ ]:
# Cast tensor into the given dtype parameter
def tf_cast(array, dtype):
    """
    Args:
        array (EagerTensor): tensor to be casted.
        dtype (tensorflow.python.framework.dtypes.DType): desired new type. (Should be a TF dtype!)

    Returns:
        EagerTensor: casted tensor.
    """
    # Make sure it's a tensor
    array = tf.constant(array)

    tf_cast_array = tf.cast(array, dtype)

    return tf_cast_array

In [ ]:
# Check the function
tmp_array = [1,2,3,4]
x = tf_cast(tmp_array, tf.uint32)
x

<tf.Tensor: shape=(4,), dtype=uint32, numpy=array([1, 2, 3, 4], dtype=uint32)>

Tensors can be multiplied element-wise (x * y) using `tf.multiply`

In [ ]:
# Multiply tensor1 and tensor2
def tf_multiply(tensor1, tensor2):
    """
    Args:
        tensor1 (EagerTensor): a tensor.
        tensor2 (EagerTensor): another tensor.

    Returns:
        EagerTensor: resulting tensor.
    """
    # Make sure these are tensors
    tensor1 = tf.constant(tensor1)
    tensor2 = tf.constant(tensor2)

    product = tf.multiply(tensor1, tensor2)

    return product


In [ ]:
# Check the function
tmp_1 = tf.constant(np.array([[1,2],[3,4]]))
tmp_2 = tf.constant(np.array(2))
result = tf_multiply(tmp_1, tmp_2)
result

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[2, 4],
       [6, 8]])>

## Exercise 6 - [tf.add](https://www.tensorflow.org/api_docs/python/tf/add)

Element-wise addition (x + y) of tensors can be performed as well using `tf.add`

In [ ]:
# Add tensor1 and tensor2
def tf_add(tensor1, tensor2):
    """
    Args:
        tensor1 (EagerTensor): a tensor.
        tensor2 (EagerTensor): another tensor.

    Returns:
        EagerTensor: resulting tensor.
    """
    # Ensure these are tensors
    tensor1 = tf.constant(tensor1)
    tensor2 = tf.constant(tensor2)

    total = tf.add(tensor1, tensor2)

    return total

In [ ]:
# Check the function
tmp_1 = tf.constant(np.array([1, 2, 3]))
tmp_2 = tf.constant(np.array([4, 5, 6]))
tf_add(tmp_1, tmp_2)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([5, 7, 9])>

## Gradient Tape

To implement the `tf_gradient_tape` function, we need to utilize TensorFlow's `GradientTape` API, which is crucial for automatic differentiation—computing gradients of computations with respect to some inputs. Here’s an explanation of the steps in the function based on the provided script:

1. **Initialize Gradient Tape**: This is done with `with tf.GradientTape() as t:`. TensorFlow records operations for automatic differentiation.

2. **Monitor Tensor `x`**: The `t.watch(x)` statement ensures that `x` is being tracked by `GradientTape`. This is necessary to compute gradients with respect to `x`.

3. **Define the Polynomial `y`**: We calculate `y` as `3*x**3 - 2*x**2 + x`. This polynomial operation is recorded by `GradientTape`.

4. **Sum the Elements of `y`**: The operation `z = tf.reduce_sum(y)` sums all elements of `y`, which is a crucial step as `z` becomes the scalar from which the gradient with respect to `x` is calculated.

5. **Compute the Gradient**: The gradient of `z` with respect to `x` is computed using `dz_dx = t.gradient(z, x)`. This is the derivative of the sum of `y` with respect to `x`.

6. **Return the Gradient**: The computed gradient `dz_dx` is then returned from the function.

By following these steps, the `tf_gradient_tape` function efficiently computes the gradient of a defined polynomial function with respect to its input tensor, which is an essential technique for many machine learning algorithms, particularly in training neural networks where optimization involves gradient-based techniques.

In [ ]:
def tf_gradient_tape(x):
    """
    Args:
        x (EagerTensor): a tensor.

    Returns:
        EagerTensor: Derivative of z with respect to the input tensor x.
    """
    with tf.GradientTape() as t:
      # Record the actions performed on tensor x with `watch`
      t.watch(x)

      # Define a polynomial of form 3x^3 - 2x^2 + x
      y = 3*x**3 - 2*x**2 + x

      # Obtain the sum of the elements in variable y
      z = tf.reduce_sum(y)

    # Get the derivative of z with respect to the original input tensor x
    dz_dx = t.gradient(z, x)

    return dz_dx

In [ ]:
# Check the function
tmp_x = tf.constant(2.0)
dz_dx = tf_gradient_tape(tmp_x)
result = dz_dx.numpy()
result

29.0