# Basic Tensors

In this notebook, we will explore some of the fundamental operations that can be performed on tensors. This session is designed to help us understand how tensors function within computational graphs and how various tensor manipulations can be applied to data science and machine learning tasks. By engaging with these basic operations, we'll gain practical insights into tensor properties, manipulation techniques, and their application in more complex algorithms. Let's dive into the practical aspects of tensors to enhance our proficiency in handling these versatile data structures.

## Imports

In [ ]:
import tensorflow as tf
import numpy as np

## Some Basic Tensor Operations

Let's create a single-dimension numpy array of size 25, containing values ranging from 0 to 24. This array will allow us to perform a variety of operations, enhancing our understanding of how numpy handles numerical data efficiently. We'll explore tasks such as indexing, slicing, and applying mathematical functions to the array elements, which are fundamental skills for any data science or machine learning application. Let's begin by setting up the array and then proceed with some basic manipulations.

In [ ]:
# Create a 1D uint8 NumPy array comprising of first 25 natural numbers
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Now that we have our 1-D array, the next step is to convert this array into a `tensor`. After performing this conversion, it's important to take a moment to inspect the properties and information of the newly created tensor. This examination will help us understand the structure, data type, and shape of the tensor, providing insights into how tensors operate differently from numpy arrays and preparing us for more advanced operations and manipulations in tensor-based computing environments. Let's proceed with this conversion and then delve into the details of our tensor.








In [ ]:
# Convert NumPy array to Tensor using `tf.constant`
x = tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

Next, we'll square each value in the tensor `x` element-wise. This simple operation will allow us to see how tensors process arithmetic computations. Let’s perform this and check the results.

In [ ]:
# Square the input tensor x
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

One key feature of tensors is their ability to be reshaped. When reshaping, it's crucial to select dimensions that accommodate all the values of the tensor without altering the data itself. This flexibility allows us to adapt the tensor's structure for various data processing and machine learning tasks efficiently. Let's proceed by adjusting the shape of our tensor to better suit our needs.

In [ ]:
# Reshape tensor x into a 5 x 5 matrix.
x = tf.reshape(x, (5, 5))
x

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

When reshaping a tensor, it's important to select a shape that can be exactly filled with the tensor's values. Choosing an incompatible shape will result in an error because the total number of elements must remain constant. If we encounter an error we should :

- Observe the error message closely to understand why the reshaping failed.
- Adjust the shape tuple we pass to the shape parameter to ensure it matches the total number of elements in the tensor.


This process will help us learn to handle tensor dimensions effectively, ensuring smooth data manipulation and preparation for further analysis or modeling tasks. Let's try this out and make the necessary adjustments to avoid any errors.

In [ ]:
# Look at the error
# Change the input to `shape` to avoid an error
tmp = tf.constant([1,2,3,4])
tf.reshape(tmp, shape=(2,3))

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 4 values, but the requested shape has 6 [Op:Reshape]

Like reshaping, we can also modify the data type of the values within a tensor. Changing the data type is particularly useful when we need to ensure compatibility with certain mathematical operations that require a specific type, or when optimizing performance by using types that consume less memory. Let’s proceed to change the data type from int to float in our tensor to accommodate these needs. This conversion is straightforward but crucial for maintaining precision in computations and ensuring the smooth integration of tensor operations.

In [ ]:
# Cast tensor x into float32. Notice the change in the dtype.
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

Next, we'll create a single-value float tensor. This will serve as a practical introduction to the concept of `broadcasting`. Broadcasting is a powerful mechanism that allows TensorFlow to work with tensors of different shapes by automatically expanding the smaller tensor along the larger tensor's dimensions without using extra memory. By observing how this single-value tensor interacts with another tensor of a larger size, we can better understand how `broadcasting` simplifies operations across different shaped tensors. Let's proceed with this setup and witness `broadcasting` in action.

In [ ]:
# Let's define a constant and see how broadcasting works in the following cell.
y = tf.constant(2, dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

Next, we'll multiply tensors `x` and `y` together. This will demonstrate how tensor multiplication is handled and allow us to inspect the results to understand the process better. Let's proceed and observe the outcome.

In [ ]:
# Multiply tensor `x` and `y`. `y` is multiplied to each element of x.
result = tf.multiply(x, y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.],
       [  50.,   72.,   98.,  128.,  162.],
       [ 200.,  242.,  288.,  338.,  392.],
       [ 450.,  512.,  578.,  648.,  722.],
       [ 800.,  882.,  968., 1058., 1152.]], dtype=float32)>

Let's re-initialize `y` to a tensor with more values. This adjustment will allow us to explore operations involving tensors of different sizes or to prepare for more complex manipulations.

In [ ]:
# Now let's define an array that matches the number of row elements in the `x` array.
y = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [ ]:
# Let's see first the contents of `x` again.
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

Next, we'll add the tensors x and y together. This will help us see how TensorFlow handles addition between tensors, especially looking at how each corresponding element is combined.

In [ ]:
# Add tensor `x` and `y`. `y` is added element wise to each row of `x`.
result = x + y
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.,   3.,   7.,  13.,  21.],
       [ 26.,  38.,  52.,  68.,  86.],
       [101., 123., 147., 173., 201.],
       [226., 258., 292., 328., 366.],
       [401., 443., 487., 533., 581.]], dtype=float32)>

### The shape parameter for tf.constant

When using `tf.constant()`, we can transform a 1D array into a multi-dimensional array by specifying the `shape` parameter. This feature is useful for structuring our data to fit specific modeling or computational needs.

In [ ]:
tf.constant([1,2,3,4], shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### The shape parameter for tf.Variable

Note that when using `tf.Variable()`, the shape of the tensor is derived from the shape of the input array. Unlike `tf.constant()`, setting the `shape` parameter to something other than None when creating a `tf.Variable` will not reshape a 1D array into a multi-dimensional array. Attempting to do so will result in a `ValueError`. This distinction is important to remember for correctly initializing tensors as variables without encountering errors.

In [ ]:
try:
    # This will produce a ValueError
    tf.Variable([1,2,3,4], shape=(2,2))
except ValueError as v:
    # See what the ValueError says
    print(v)

In this `tf.Variable` creation, the initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).
